//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniTorrentService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFile
    {
        public string Username { get; set; }
        public string Name { get; set; }
    
        public virtual User User { get; set; }
        public virtual File File { get; set; }
    }
}
